### PR TITLE
Update to OIDN 2.1.0

### PR DESCRIPTION
**Pull request by pypoulp**
Update to new OIDN 2.1.0. Updated libs for all platforms provided, but only tested on Windows.

Only CPU device supported as before, Cuda & others would probably require bindings for the buffer API.

Also edited the CornellBox test so it finds the module based on here, and not cwd.

### CODE REVIEW

**Comment by sxysxy** [comment]
Wow, Thank you, I'm going to test it on Linux and macOS (with M1 Max Chip). and strip the alpha version tag, making it to be a formal release version.

**Comment by pypoulp** [comment]
Thx for the merge, is was straight forward update, they just change the functions names a bit :) 

The cuda backend is really fast. I'm wondering what would be the best way to bind it. Maybe through the buffer api.
Or maybe with Cupy, I saw that Cupy offer quite low level access : https://docs.cupy.dev/en/stable/reference/generated/cupy.cuda.MemoryPointer.html

I'm not sure if it would be possible to pass the array directly to OIDN cuda like that.

**Comment by sxysxy** [comment]
> Thx for the merge, is was straight forward update, they just change the functions names a bit :)
> 
> The cuda backend is really fast. I'm wondering what would be the best way to bind it. Maybe through the buffer api. Or maybe with Cupy, I saw that Cupy offer quite low level access : https://docs.cupy.dev/en/stable/reference/generated/cupy.cuda.MemoryPointer.html
> 
> I'm not sure if it would be possible to pass the array directly to OIDN cuda like that.

Well, as for CUDA, PyTorch tensors could be used as buffers via their's _cdata property(_cdata returns an address pointing to the row-major contiguous buffers.). Compared with CUPY, pytorch tensors provide convenient interfaces for high-level array and arithmetical operations, also, tensors could be easily converted to numpy arrays or PIL Images.  I can make this update to support CUDA backend.

But PyTorch is a huge third-party library, Maybe I would also add an alternative implementation based on CUPY.

**Comment by sxysxy** [comment]
And thanks for your contributions.

**Comment by pypoulp** [comment]
Np, I'll test stuff for GPU device on my side as well, pretty interesting topic.

It seems that Cupy / PyTorch support some kind of interoperability through `__cuda_array_interface__`
https://docs.cupy.dev/en/stable/user_guide/interoperability.html

**Comment by sxysxy** [comment]
Also some other interesting new features were introduced into the new OIDN2,1,0, I would work on it for several days to support them.

**Comment by sxysxy** [comment]
A new version is preparing. Pythonic APIs is available, the example could be written in:

```python
from pathlib import Path
import sys
import numpy as np
from PIL import Image

here = Path(__file__).parent.absolute()
sys.path.append(here.parent.parent.absolute().as_posix())

import oidn

with oidn.Device('cpu') as device, oidn.Filter(device, 'RT') as filter:
    input = oidn.Buffer.load(device, Image.open((here / "CornellBoxNoisy.png").as_posix()), div255=True)
    output = oidn.Buffer.create(input.width, input.height, device=device)
    filter.set_image("color", input)
    filter.set_image("output", output)
    filter.execute()
    Image.fromarray( np.array(np.clip(output.to_array() * 255, 0, 255), dtype=np.uint8) ).save(f"{here}/CornellBoxDenoised.png")
```

API document could be generated by generate_doc.py

But I don't know why I failed to create a device with the flag OIDN_DEVICE_TYPE_CUDA(oidn.Device('cuda')), GetDeviceError returns it is not supported. My cuda toolkit version installed in a linux server is 12.2.0

**Comment by pypoulp** [comment]
Wow, Great ! 

I love the "lazy load' GPU way that would allow to use Cupy / Pytorch Independantly. Maybe it's just because of missing DLL ? In this version of OIDN, each backend has its own DLL: https://www.openimagedenoise.org/downloads.html

You can try to run the OpenDenoiseBenchmark binary with GPU backend to see if it works. There is also a SYCL backend for Intel GPUs, but I dont have one.

Ideally, the best way may be to load the specific backend DLL on demand, on avoid loading everything at init. I suspect OIDN is doing it if needed DLLs are in path / not sure with ctypes.

It would be nice to have a shortcut to enable hdr (boolean filter option), as it's often used in real world on 3D render denoising.
In case of hdr, there is a scale factor that can be set, but i'm not sure if OIDN takes care or it automatically.

I tried to compute it like that, but I dont see much differences compared to just hdr enabled : 

```python
max_red = np.max(beauty[..., 0])
max_green = np.max(beauty[..., 1])
max_blue = np.max(beauty[..., 2])
max_luma = 0.2126 * max_red + 0.7152 * max_green + 0.0722 * max_blue
input_scale = 100.0 / max_luma
```

About the `div255` option, I would suggest `normalize` name that is a bit more Python friendly and 

```python
if normalize:
    if  x_np.dtype  == np.uint8:
        x_np /= 255.0
    elif x_np.dtype == np.uint16:
        x_np /= 65536.0
```

Also maybe  `get_c_contiguous` could be `is_c_contiguous`

Great update !

**Pull request merged**
